### ISSUE TITLE
Import-Module Error

### ISSUE THREAD

**Issue by lordofthefries** [Infocyte/PSHunt#1]
When attempting to use "Import-Module PSHunt", I receive the below:

`import-module : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At line:1 char:1
- import-module PSHunt
- ~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
  - FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand`

**Comment by Pinchequay** [comment]
Module folders \Lib\Posh-VirusTotal and \Lib\PSReflect were empty for me after unzipping.  

Manually downloaded the files and extracted to their respective folders.

https://github.com/darkoperator/Posh-VirusTotal
https://github.com/mattifestation/PSReflect

The module imported without error after that.

**Comment by singlethreaded** [comment]
Realized I have no idea what I'm doing with nested submodules.  I removed the 16000 entry and made them standard commits.  I'll update Posh-VirusTotal and PSReflect manually when those projects are updated until I figure out how to make this easier to distribute submodules.
